# Generated by Django 5.2.7 on 2025-10-22 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LendingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True, help_text="Время возврата книги", null=True
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="книга",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лендинг",
                "verbose_name_plural": "Лендинги",
            },
        ),
    ]
